
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FocusRecord` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model FocusRecord
 * 
 */
export type FocusRecordModel = runtime.Types.Result.DefaultSelection<Prisma.$FocusRecordPayload>

export type AggregateFocusRecord = {
  _count: FocusRecordCountAggregateOutputType | null
  _avg: FocusRecordAvgAggregateOutputType | null
  _sum: FocusRecordSumAggregateOutputType | null
  _min: FocusRecordMinAggregateOutputType | null
  _max: FocusRecordMaxAggregateOutputType | null
}

export type FocusRecordAvgAggregateOutputType = {
  duration: number | null
}

export type FocusRecordSumAggregateOutputType = {
  duration: number | null
}

export type FocusRecordMinAggregateOutputType = {
  id: string | null
  type: $Enums.FocusType | null
  duration: number | null
  startedAt: Date | null
  endedAt: Date | null
  userId: string | null
  taskId: string | null
  createdAt: Date | null
}

export type FocusRecordMaxAggregateOutputType = {
  id: string | null
  type: $Enums.FocusType | null
  duration: number | null
  startedAt: Date | null
  endedAt: Date | null
  userId: string | null
  taskId: string | null
  createdAt: Date | null
}

export type FocusRecordCountAggregateOutputType = {
  id: number
  type: number
  duration: number
  startedAt: number
  endedAt: number
  userId: number
  taskId: number
  createdAt: number
  _all: number
}


export type FocusRecordAvgAggregateInputType = {
  duration?: true
}

export type FocusRecordSumAggregateInputType = {
  duration?: true
}

export type FocusRecordMinAggregateInputType = {
  id?: true
  type?: true
  duration?: true
  startedAt?: true
  endedAt?: true
  userId?: true
  taskId?: true
  createdAt?: true
}

export type FocusRecordMaxAggregateInputType = {
  id?: true
  type?: true
  duration?: true
  startedAt?: true
  endedAt?: true
  userId?: true
  taskId?: true
  createdAt?: true
}

export type FocusRecordCountAggregateInputType = {
  id?: true
  type?: true
  duration?: true
  startedAt?: true
  endedAt?: true
  userId?: true
  taskId?: true
  createdAt?: true
  _all?: true
}

export type FocusRecordAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FocusRecord to aggregate.
   */
  where?: Prisma.FocusRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusRecords to fetch.
   */
  orderBy?: Prisma.FocusRecordOrderByWithRelationInput | Prisma.FocusRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FocusRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FocusRecords
  **/
  _count?: true | FocusRecordCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FocusRecordAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FocusRecordSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FocusRecordMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FocusRecordMaxAggregateInputType
}

export type GetFocusRecordAggregateType<T extends FocusRecordAggregateArgs> = {
      [P in keyof T & keyof AggregateFocusRecord]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFocusRecord[P]>
    : Prisma.GetScalarType<T[P], AggregateFocusRecord[P]>
}




export type FocusRecordGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FocusRecordWhereInput
  orderBy?: Prisma.FocusRecordOrderByWithAggregationInput | Prisma.FocusRecordOrderByWithAggregationInput[]
  by: Prisma.FocusRecordScalarFieldEnum[] | Prisma.FocusRecordScalarFieldEnum
  having?: Prisma.FocusRecordScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FocusRecordCountAggregateInputType | true
  _avg?: FocusRecordAvgAggregateInputType
  _sum?: FocusRecordSumAggregateInputType
  _min?: FocusRecordMinAggregateInputType
  _max?: FocusRecordMaxAggregateInputType
}

export type FocusRecordGroupByOutputType = {
  id: string
  type: $Enums.FocusType
  duration: number
  startedAt: Date
  endedAt: Date | null
  userId: string
  taskId: string | null
  createdAt: Date
  _count: FocusRecordCountAggregateOutputType | null
  _avg: FocusRecordAvgAggregateOutputType | null
  _sum: FocusRecordSumAggregateOutputType | null
  _min: FocusRecordMinAggregateOutputType | null
  _max: FocusRecordMaxAggregateOutputType | null
}

export type GetFocusRecordGroupByPayload<T extends FocusRecordGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FocusRecordGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FocusRecordGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FocusRecordGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FocusRecordGroupByOutputType[P]>
      }
    >
  >



export type FocusRecordWhereInput = {
  AND?: Prisma.FocusRecordWhereInput | Prisma.FocusRecordWhereInput[]
  OR?: Prisma.FocusRecordWhereInput[]
  NOT?: Prisma.FocusRecordWhereInput | Prisma.FocusRecordWhereInput[]
  id?: Prisma.StringFilter<"FocusRecord"> | string
  type?: Prisma.EnumFocusTypeFilter<"FocusRecord"> | $Enums.FocusType
  duration?: Prisma.IntFilter<"FocusRecord"> | number
  startedAt?: Prisma.DateTimeFilter<"FocusRecord"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"FocusRecord"> | Date | string | null
  userId?: Prisma.StringFilter<"FocusRecord"> | string
  taskId?: Prisma.StringNullableFilter<"FocusRecord"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FocusRecord"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  task?: Prisma.XOR<Prisma.TaskNullableScalarRelationFilter, Prisma.TaskWhereInput> | null
}

export type FocusRecordOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  task?: Prisma.TaskOrderByWithRelationInput
}

export type FocusRecordWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FocusRecordWhereInput | Prisma.FocusRecordWhereInput[]
  OR?: Prisma.FocusRecordWhereInput[]
  NOT?: Prisma.FocusRecordWhereInput | Prisma.FocusRecordWhereInput[]
  type?: Prisma.EnumFocusTypeFilter<"FocusRecord"> | $Enums.FocusType
  duration?: Prisma.IntFilter<"FocusRecord"> | number
  startedAt?: Prisma.DateTimeFilter<"FocusRecord"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"FocusRecord"> | Date | string | null
  userId?: Prisma.StringFilter<"FocusRecord"> | string
  taskId?: Prisma.StringNullableFilter<"FocusRecord"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FocusRecord"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  task?: Prisma.XOR<Prisma.TaskNullableScalarRelationFilter, Prisma.TaskWhereInput> | null
}, "id">

export type FocusRecordOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.FocusRecordCountOrderByAggregateInput
  _avg?: Prisma.FocusRecordAvgOrderByAggregateInput
  _max?: Prisma.FocusRecordMaxOrderByAggregateInput
  _min?: Prisma.FocusRecordMinOrderByAggregateInput
  _sum?: Prisma.FocusRecordSumOrderByAggregateInput
}

export type FocusRecordScalarWhereWithAggregatesInput = {
  AND?: Prisma.FocusRecordScalarWhereWithAggregatesInput | Prisma.FocusRecordScalarWhereWithAggregatesInput[]
  OR?: Prisma.FocusRecordScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FocusRecordScalarWhereWithAggregatesInput | Prisma.FocusRecordScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FocusRecord"> | string
  type?: Prisma.EnumFocusTypeWithAggregatesFilter<"FocusRecord"> | $Enums.FocusType
  duration?: Prisma.IntWithAggregatesFilter<"FocusRecord"> | number
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"FocusRecord"> | Date | string
  endedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"FocusRecord"> | Date | string | null
  userId?: Prisma.StringWithAggregatesFilter<"FocusRecord"> | string
  taskId?: Prisma.StringNullableWithAggregatesFilter<"FocusRecord"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FocusRecord"> | Date | string
}

export type FocusRecordCreateInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutFocusRecordsInput
  task?: Prisma.TaskCreateNestedOneWithoutFocusRecordsInput
}

export type FocusRecordUncheckedCreateInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  userId: string
  taskId?: string | null
  createdAt?: Date | string
}

export type FocusRecordUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutFocusRecordsNestedInput
  task?: Prisma.TaskUpdateOneWithoutFocusRecordsNestedInput
}

export type FocusRecordUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusRecordCreateManyInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  userId: string
  taskId?: string | null
  createdAt?: Date | string
}

export type FocusRecordUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusRecordUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusRecordListRelationFilter = {
  every?: Prisma.FocusRecordWhereInput
  some?: Prisma.FocusRecordWhereInput
  none?: Prisma.FocusRecordWhereInput
}

export type FocusRecordOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FocusRecordCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FocusRecordAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type FocusRecordMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FocusRecordMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FocusRecordSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type FocusRecordCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutUserInput, Prisma.FocusRecordUncheckedCreateWithoutUserInput> | Prisma.FocusRecordCreateWithoutUserInput[] | Prisma.FocusRecordUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutUserInput | Prisma.FocusRecordCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FocusRecordCreateManyUserInputEnvelope
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
}

export type FocusRecordUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutUserInput, Prisma.FocusRecordUncheckedCreateWithoutUserInput> | Prisma.FocusRecordCreateWithoutUserInput[] | Prisma.FocusRecordUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutUserInput | Prisma.FocusRecordCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.FocusRecordCreateManyUserInputEnvelope
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
}

export type FocusRecordUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutUserInput, Prisma.FocusRecordUncheckedCreateWithoutUserInput> | Prisma.FocusRecordCreateWithoutUserInput[] | Prisma.FocusRecordUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutUserInput | Prisma.FocusRecordCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FocusRecordUpsertWithWhereUniqueWithoutUserInput | Prisma.FocusRecordUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FocusRecordCreateManyUserInputEnvelope
  set?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  disconnect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  delete?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  update?: Prisma.FocusRecordUpdateWithWhereUniqueWithoutUserInput | Prisma.FocusRecordUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FocusRecordUpdateManyWithWhereWithoutUserInput | Prisma.FocusRecordUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FocusRecordScalarWhereInput | Prisma.FocusRecordScalarWhereInput[]
}

export type FocusRecordUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutUserInput, Prisma.FocusRecordUncheckedCreateWithoutUserInput> | Prisma.FocusRecordCreateWithoutUserInput[] | Prisma.FocusRecordUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutUserInput | Prisma.FocusRecordCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.FocusRecordUpsertWithWhereUniqueWithoutUserInput | Prisma.FocusRecordUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.FocusRecordCreateManyUserInputEnvelope
  set?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  disconnect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  delete?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  update?: Prisma.FocusRecordUpdateWithWhereUniqueWithoutUserInput | Prisma.FocusRecordUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.FocusRecordUpdateManyWithWhereWithoutUserInput | Prisma.FocusRecordUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.FocusRecordScalarWhereInput | Prisma.FocusRecordScalarWhereInput[]
}

export type FocusRecordCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutTaskInput, Prisma.FocusRecordUncheckedCreateWithoutTaskInput> | Prisma.FocusRecordCreateWithoutTaskInput[] | Prisma.FocusRecordUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutTaskInput | Prisma.FocusRecordCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.FocusRecordCreateManyTaskInputEnvelope
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
}

export type FocusRecordUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutTaskInput, Prisma.FocusRecordUncheckedCreateWithoutTaskInput> | Prisma.FocusRecordCreateWithoutTaskInput[] | Prisma.FocusRecordUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutTaskInput | Prisma.FocusRecordCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.FocusRecordCreateManyTaskInputEnvelope
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
}

export type FocusRecordUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutTaskInput, Prisma.FocusRecordUncheckedCreateWithoutTaskInput> | Prisma.FocusRecordCreateWithoutTaskInput[] | Prisma.FocusRecordUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutTaskInput | Prisma.FocusRecordCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.FocusRecordUpsertWithWhereUniqueWithoutTaskInput | Prisma.FocusRecordUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.FocusRecordCreateManyTaskInputEnvelope
  set?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  disconnect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  delete?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  update?: Prisma.FocusRecordUpdateWithWhereUniqueWithoutTaskInput | Prisma.FocusRecordUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.FocusRecordUpdateManyWithWhereWithoutTaskInput | Prisma.FocusRecordUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.FocusRecordScalarWhereInput | Prisma.FocusRecordScalarWhereInput[]
}

export type FocusRecordUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.FocusRecordCreateWithoutTaskInput, Prisma.FocusRecordUncheckedCreateWithoutTaskInput> | Prisma.FocusRecordCreateWithoutTaskInput[] | Prisma.FocusRecordUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.FocusRecordCreateOrConnectWithoutTaskInput | Prisma.FocusRecordCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.FocusRecordUpsertWithWhereUniqueWithoutTaskInput | Prisma.FocusRecordUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.FocusRecordCreateManyTaskInputEnvelope
  set?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  disconnect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  delete?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  connect?: Prisma.FocusRecordWhereUniqueInput | Prisma.FocusRecordWhereUniqueInput[]
  update?: Prisma.FocusRecordUpdateWithWhereUniqueWithoutTaskInput | Prisma.FocusRecordUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.FocusRecordUpdateManyWithWhereWithoutTaskInput | Prisma.FocusRecordUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.FocusRecordScalarWhereInput | Prisma.FocusRecordScalarWhereInput[]
}

export type EnumFocusTypeFieldUpdateOperationsInput = {
  set?: $Enums.FocusType
}

export type FocusRecordCreateWithoutUserInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  createdAt?: Date | string
  task?: Prisma.TaskCreateNestedOneWithoutFocusRecordsInput
}

export type FocusRecordUncheckedCreateWithoutUserInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  taskId?: string | null
  createdAt?: Date | string
}

export type FocusRecordCreateOrConnectWithoutUserInput = {
  where: Prisma.FocusRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.FocusRecordCreateWithoutUserInput, Prisma.FocusRecordUncheckedCreateWithoutUserInput>
}

export type FocusRecordCreateManyUserInputEnvelope = {
  data: Prisma.FocusRecordCreateManyUserInput | Prisma.FocusRecordCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type FocusRecordUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.FocusRecordWhereUniqueInput
  update: Prisma.XOR<Prisma.FocusRecordUpdateWithoutUserInput, Prisma.FocusRecordUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.FocusRecordCreateWithoutUserInput, Prisma.FocusRecordUncheckedCreateWithoutUserInput>
}

export type FocusRecordUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.FocusRecordWhereUniqueInput
  data: Prisma.XOR<Prisma.FocusRecordUpdateWithoutUserInput, Prisma.FocusRecordUncheckedUpdateWithoutUserInput>
}

export type FocusRecordUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.FocusRecordScalarWhereInput
  data: Prisma.XOR<Prisma.FocusRecordUpdateManyMutationInput, Prisma.FocusRecordUncheckedUpdateManyWithoutUserInput>
}

export type FocusRecordScalarWhereInput = {
  AND?: Prisma.FocusRecordScalarWhereInput | Prisma.FocusRecordScalarWhereInput[]
  OR?: Prisma.FocusRecordScalarWhereInput[]
  NOT?: Prisma.FocusRecordScalarWhereInput | Prisma.FocusRecordScalarWhereInput[]
  id?: Prisma.StringFilter<"FocusRecord"> | string
  type?: Prisma.EnumFocusTypeFilter<"FocusRecord"> | $Enums.FocusType
  duration?: Prisma.IntFilter<"FocusRecord"> | number
  startedAt?: Prisma.DateTimeFilter<"FocusRecord"> | Date | string
  endedAt?: Prisma.DateTimeNullableFilter<"FocusRecord"> | Date | string | null
  userId?: Prisma.StringFilter<"FocusRecord"> | string
  taskId?: Prisma.StringNullableFilter<"FocusRecord"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FocusRecord"> | Date | string
}

export type FocusRecordCreateWithoutTaskInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutFocusRecordsInput
}

export type FocusRecordUncheckedCreateWithoutTaskInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  userId: string
  createdAt?: Date | string
}

export type FocusRecordCreateOrConnectWithoutTaskInput = {
  where: Prisma.FocusRecordWhereUniqueInput
  create: Prisma.XOR<Prisma.FocusRecordCreateWithoutTaskInput, Prisma.FocusRecordUncheckedCreateWithoutTaskInput>
}

export type FocusRecordCreateManyTaskInputEnvelope = {
  data: Prisma.FocusRecordCreateManyTaskInput | Prisma.FocusRecordCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type FocusRecordUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.FocusRecordWhereUniqueInput
  update: Prisma.XOR<Prisma.FocusRecordUpdateWithoutTaskInput, Prisma.FocusRecordUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.FocusRecordCreateWithoutTaskInput, Prisma.FocusRecordUncheckedCreateWithoutTaskInput>
}

export type FocusRecordUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.FocusRecordWhereUniqueInput
  data: Prisma.XOR<Prisma.FocusRecordUpdateWithoutTaskInput, Prisma.FocusRecordUncheckedUpdateWithoutTaskInput>
}

export type FocusRecordUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.FocusRecordScalarWhereInput
  data: Prisma.XOR<Prisma.FocusRecordUpdateManyMutationInput, Prisma.FocusRecordUncheckedUpdateManyWithoutTaskInput>
}

export type FocusRecordCreateManyUserInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  taskId?: string | null
  createdAt?: Date | string
}

export type FocusRecordUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  task?: Prisma.TaskUpdateOneWithoutFocusRecordsNestedInput
}

export type FocusRecordUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusRecordUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  taskId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusRecordCreateManyTaskInput = {
  id?: string
  type?: $Enums.FocusType
  duration: number
  startedAt: Date | string
  endedAt?: Date | string | null
  userId: string
  createdAt?: Date | string
}

export type FocusRecordUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutFocusRecordsNestedInput
}

export type FocusRecordUncheckedUpdateWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FocusRecordUncheckedUpdateManyWithoutTaskInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumFocusTypeFieldUpdateOperationsInput | $Enums.FocusType
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FocusRecordSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  duration?: boolean
  startedAt?: boolean
  endedAt?: boolean
  userId?: boolean
  taskId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.FocusRecord$taskArgs<ExtArgs>
}, ExtArgs["result"]["focusRecord"]>

export type FocusRecordSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  duration?: boolean
  startedAt?: boolean
  endedAt?: boolean
  userId?: boolean
  taskId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.FocusRecord$taskArgs<ExtArgs>
}, ExtArgs["result"]["focusRecord"]>

export type FocusRecordSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  duration?: boolean
  startedAt?: boolean
  endedAt?: boolean
  userId?: boolean
  taskId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.FocusRecord$taskArgs<ExtArgs>
}, ExtArgs["result"]["focusRecord"]>

export type FocusRecordSelectScalar = {
  id?: boolean
  type?: boolean
  duration?: boolean
  startedAt?: boolean
  endedAt?: boolean
  userId?: boolean
  taskId?: boolean
  createdAt?: boolean
}

export type FocusRecordOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "duration" | "startedAt" | "endedAt" | "userId" | "taskId" | "createdAt", ExtArgs["result"]["focusRecord"]>
export type FocusRecordInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.FocusRecord$taskArgs<ExtArgs>
}
export type FocusRecordIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.FocusRecord$taskArgs<ExtArgs>
}
export type FocusRecordIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  task?: boolean | Prisma.FocusRecord$taskArgs<ExtArgs>
}

export type $FocusRecordPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FocusRecord"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    task: Prisma.$TaskPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: $Enums.FocusType
    duration: number
    startedAt: Date
    endedAt: Date | null
    userId: string
    taskId: string | null
    createdAt: Date
  }, ExtArgs["result"]["focusRecord"]>
  composites: {}
}

export type FocusRecordGetPayload<S extends boolean | null | undefined | FocusRecordDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload, S>

export type FocusRecordCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FocusRecordFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FocusRecordCountAggregateInputType | true
  }

export interface FocusRecordDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FocusRecord'], meta: { name: 'FocusRecord' } }
  /**
   * Find zero or one FocusRecord that matches the filter.
   * @param {FocusRecordFindUniqueArgs} args - Arguments to find a FocusRecord
   * @example
   * // Get one FocusRecord
   * const focusRecord = await prisma.focusRecord.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FocusRecordFindUniqueArgs>(args: Prisma.SelectSubset<T, FocusRecordFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FocusRecord that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FocusRecordFindUniqueOrThrowArgs} args - Arguments to find a FocusRecord
   * @example
   * // Get one FocusRecord
   * const focusRecord = await prisma.focusRecord.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FocusRecordFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FocusRecordFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FocusRecord that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusRecordFindFirstArgs} args - Arguments to find a FocusRecord
   * @example
   * // Get one FocusRecord
   * const focusRecord = await prisma.focusRecord.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FocusRecordFindFirstArgs>(args?: Prisma.SelectSubset<T, FocusRecordFindFirstArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FocusRecord that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusRecordFindFirstOrThrowArgs} args - Arguments to find a FocusRecord
   * @example
   * // Get one FocusRecord
   * const focusRecord = await prisma.focusRecord.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FocusRecordFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FocusRecordFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FocusRecords that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusRecordFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FocusRecords
   * const focusRecords = await prisma.focusRecord.findMany()
   * 
   * // Get first 10 FocusRecords
   * const focusRecords = await prisma.focusRecord.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const focusRecordWithIdOnly = await prisma.focusRecord.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FocusRecordFindManyArgs>(args?: Prisma.SelectSubset<T, FocusRecordFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FocusRecord.
   * @param {FocusRecordCreateArgs} args - Arguments to create a FocusRecord.
   * @example
   * // Create one FocusRecord
   * const FocusRecord = await prisma.focusRecord.create({
   *   data: {
   *     // ... data to create a FocusRecord
   *   }
   * })
   * 
   */
  create<T extends FocusRecordCreateArgs>(args: Prisma.SelectSubset<T, FocusRecordCreateArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FocusRecords.
   * @param {FocusRecordCreateManyArgs} args - Arguments to create many FocusRecords.
   * @example
   * // Create many FocusRecords
   * const focusRecord = await prisma.focusRecord.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FocusRecordCreateManyArgs>(args?: Prisma.SelectSubset<T, FocusRecordCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FocusRecords and returns the data saved in the database.
   * @param {FocusRecordCreateManyAndReturnArgs} args - Arguments to create many FocusRecords.
   * @example
   * // Create many FocusRecords
   * const focusRecord = await prisma.focusRecord.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FocusRecords and only return the `id`
   * const focusRecordWithIdOnly = await prisma.focusRecord.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FocusRecordCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FocusRecordCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FocusRecord.
   * @param {FocusRecordDeleteArgs} args - Arguments to delete one FocusRecord.
   * @example
   * // Delete one FocusRecord
   * const FocusRecord = await prisma.focusRecord.delete({
   *   where: {
   *     // ... filter to delete one FocusRecord
   *   }
   * })
   * 
   */
  delete<T extends FocusRecordDeleteArgs>(args: Prisma.SelectSubset<T, FocusRecordDeleteArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FocusRecord.
   * @param {FocusRecordUpdateArgs} args - Arguments to update one FocusRecord.
   * @example
   * // Update one FocusRecord
   * const focusRecord = await prisma.focusRecord.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FocusRecordUpdateArgs>(args: Prisma.SelectSubset<T, FocusRecordUpdateArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FocusRecords.
   * @param {FocusRecordDeleteManyArgs} args - Arguments to filter FocusRecords to delete.
   * @example
   * // Delete a few FocusRecords
   * const { count } = await prisma.focusRecord.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FocusRecordDeleteManyArgs>(args?: Prisma.SelectSubset<T, FocusRecordDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FocusRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusRecordUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FocusRecords
   * const focusRecord = await prisma.focusRecord.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FocusRecordUpdateManyArgs>(args: Prisma.SelectSubset<T, FocusRecordUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FocusRecords and returns the data updated in the database.
   * @param {FocusRecordUpdateManyAndReturnArgs} args - Arguments to update many FocusRecords.
   * @example
   * // Update many FocusRecords
   * const focusRecord = await prisma.focusRecord.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FocusRecords and only return the `id`
   * const focusRecordWithIdOnly = await prisma.focusRecord.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FocusRecordUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FocusRecordUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FocusRecord.
   * @param {FocusRecordUpsertArgs} args - Arguments to update or create a FocusRecord.
   * @example
   * // Update or create a FocusRecord
   * const focusRecord = await prisma.focusRecord.upsert({
   *   create: {
   *     // ... data to create a FocusRecord
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FocusRecord we want to update
   *   }
   * })
   */
  upsert<T extends FocusRecordUpsertArgs>(args: Prisma.SelectSubset<T, FocusRecordUpsertArgs<ExtArgs>>): Prisma.Prisma__FocusRecordClient<runtime.Types.Result.GetResult<Prisma.$FocusRecordPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FocusRecords.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusRecordCountArgs} args - Arguments to filter FocusRecords to count.
   * @example
   * // Count the number of FocusRecords
   * const count = await prisma.focusRecord.count({
   *   where: {
   *     // ... the filter for the FocusRecords we want to count
   *   }
   * })
  **/
  count<T extends FocusRecordCountArgs>(
    args?: Prisma.Subset<T, FocusRecordCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FocusRecordCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FocusRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusRecordAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FocusRecordAggregateArgs>(args: Prisma.Subset<T, FocusRecordAggregateArgs>): Prisma.PrismaPromise<GetFocusRecordAggregateType<T>>

  /**
   * Group by FocusRecord.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FocusRecordGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FocusRecordGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FocusRecordGroupByArgs['orderBy'] }
      : { orderBy?: FocusRecordGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FocusRecordGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFocusRecordGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FocusRecord model
 */
readonly fields: FocusRecordFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FocusRecord.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FocusRecordClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.FocusRecord$taskArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FocusRecord$taskArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FocusRecord model
 */
export interface FocusRecordFieldRefs {
  readonly id: Prisma.FieldRef<"FocusRecord", 'String'>
  readonly type: Prisma.FieldRef<"FocusRecord", 'FocusType'>
  readonly duration: Prisma.FieldRef<"FocusRecord", 'Int'>
  readonly startedAt: Prisma.FieldRef<"FocusRecord", 'DateTime'>
  readonly endedAt: Prisma.FieldRef<"FocusRecord", 'DateTime'>
  readonly userId: Prisma.FieldRef<"FocusRecord", 'String'>
  readonly taskId: Prisma.FieldRef<"FocusRecord", 'String'>
  readonly createdAt: Prisma.FieldRef<"FocusRecord", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FocusRecord findUnique
 */
export type FocusRecordFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * Filter, which FocusRecord to fetch.
   */
  where: Prisma.FocusRecordWhereUniqueInput
}

/**
 * FocusRecord findUniqueOrThrow
 */
export type FocusRecordFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * Filter, which FocusRecord to fetch.
   */
  where: Prisma.FocusRecordWhereUniqueInput
}

/**
 * FocusRecord findFirst
 */
export type FocusRecordFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * Filter, which FocusRecord to fetch.
   */
  where?: Prisma.FocusRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusRecords to fetch.
   */
  orderBy?: Prisma.FocusRecordOrderByWithRelationInput | Prisma.FocusRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FocusRecords.
   */
  cursor?: Prisma.FocusRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusRecords.
   */
  distinct?: Prisma.FocusRecordScalarFieldEnum | Prisma.FocusRecordScalarFieldEnum[]
}

/**
 * FocusRecord findFirstOrThrow
 */
export type FocusRecordFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * Filter, which FocusRecord to fetch.
   */
  where?: Prisma.FocusRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusRecords to fetch.
   */
  orderBy?: Prisma.FocusRecordOrderByWithRelationInput | Prisma.FocusRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FocusRecords.
   */
  cursor?: Prisma.FocusRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusRecords.
   */
  distinct?: Prisma.FocusRecordScalarFieldEnum | Prisma.FocusRecordScalarFieldEnum[]
}

/**
 * FocusRecord findMany
 */
export type FocusRecordFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * Filter, which FocusRecords to fetch.
   */
  where?: Prisma.FocusRecordWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FocusRecords to fetch.
   */
  orderBy?: Prisma.FocusRecordOrderByWithRelationInput | Prisma.FocusRecordOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FocusRecords.
   */
  cursor?: Prisma.FocusRecordWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FocusRecords from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FocusRecords.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FocusRecords.
   */
  distinct?: Prisma.FocusRecordScalarFieldEnum | Prisma.FocusRecordScalarFieldEnum[]
}

/**
 * FocusRecord create
 */
export type FocusRecordCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * The data needed to create a FocusRecord.
   */
  data: Prisma.XOR<Prisma.FocusRecordCreateInput, Prisma.FocusRecordUncheckedCreateInput>
}

/**
 * FocusRecord createMany
 */
export type FocusRecordCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FocusRecords.
   */
  data: Prisma.FocusRecordCreateManyInput | Prisma.FocusRecordCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FocusRecord createManyAndReturn
 */
export type FocusRecordCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * The data used to create many FocusRecords.
   */
  data: Prisma.FocusRecordCreateManyInput | Prisma.FocusRecordCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FocusRecord update
 */
export type FocusRecordUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * The data needed to update a FocusRecord.
   */
  data: Prisma.XOR<Prisma.FocusRecordUpdateInput, Prisma.FocusRecordUncheckedUpdateInput>
  /**
   * Choose, which FocusRecord to update.
   */
  where: Prisma.FocusRecordWhereUniqueInput
}

/**
 * FocusRecord updateMany
 */
export type FocusRecordUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FocusRecords.
   */
  data: Prisma.XOR<Prisma.FocusRecordUpdateManyMutationInput, Prisma.FocusRecordUncheckedUpdateManyInput>
  /**
   * Filter which FocusRecords to update
   */
  where?: Prisma.FocusRecordWhereInput
  /**
   * Limit how many FocusRecords to update.
   */
  limit?: number
}

/**
 * FocusRecord updateManyAndReturn
 */
export type FocusRecordUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * The data used to update FocusRecords.
   */
  data: Prisma.XOR<Prisma.FocusRecordUpdateManyMutationInput, Prisma.FocusRecordUncheckedUpdateManyInput>
  /**
   * Filter which FocusRecords to update
   */
  where?: Prisma.FocusRecordWhereInput
  /**
   * Limit how many FocusRecords to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FocusRecord upsert
 */
export type FocusRecordUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * The filter to search for the FocusRecord to update in case it exists.
   */
  where: Prisma.FocusRecordWhereUniqueInput
  /**
   * In case the FocusRecord found by the `where` argument doesn't exist, create a new FocusRecord with this data.
   */
  create: Prisma.XOR<Prisma.FocusRecordCreateInput, Prisma.FocusRecordUncheckedCreateInput>
  /**
   * In case the FocusRecord was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FocusRecordUpdateInput, Prisma.FocusRecordUncheckedUpdateInput>
}

/**
 * FocusRecord delete
 */
export type FocusRecordDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
  /**
   * Filter which FocusRecord to delete.
   */
  where: Prisma.FocusRecordWhereUniqueInput
}

/**
 * FocusRecord deleteMany
 */
export type FocusRecordDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FocusRecords to delete
   */
  where?: Prisma.FocusRecordWhereInput
  /**
   * Limit how many FocusRecords to delete.
   */
  limit?: number
}

/**
 * FocusRecord.task
 */
export type FocusRecord$taskArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Task
   */
  select?: Prisma.TaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Task
   */
  omit?: Prisma.TaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TaskInclude<ExtArgs> | null
  where?: Prisma.TaskWhereInput
}

/**
 * FocusRecord without action
 */
export type FocusRecordDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FocusRecord
   */
  select?: Prisma.FocusRecordSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FocusRecord
   */
  omit?: Prisma.FocusRecordOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FocusRecordInclude<ExtArgs> | null
}
