
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TagTask` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model TagTask
 * 
 */
export type TagTaskModel = runtime.Types.Result.DefaultSelection<Prisma.$TagTaskPayload>

export type AggregateTagTask = {
  _count: TagTaskCountAggregateOutputType | null
  _min: TagTaskMinAggregateOutputType | null
  _max: TagTaskMaxAggregateOutputType | null
}

export type TagTaskMinAggregateOutputType = {
  tagId: string | null
  taskId: string | null
}

export type TagTaskMaxAggregateOutputType = {
  tagId: string | null
  taskId: string | null
}

export type TagTaskCountAggregateOutputType = {
  tagId: number
  taskId: number
  _all: number
}


export type TagTaskMinAggregateInputType = {
  tagId?: true
  taskId?: true
}

export type TagTaskMaxAggregateInputType = {
  tagId?: true
  taskId?: true
}

export type TagTaskCountAggregateInputType = {
  tagId?: true
  taskId?: true
  _all?: true
}

export type TagTaskAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagTask to aggregate.
   */
  where?: Prisma.TagTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagTasks to fetch.
   */
  orderBy?: Prisma.TagTaskOrderByWithRelationInput | Prisma.TagTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TagTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TagTasks
  **/
  _count?: true | TagTaskCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TagTaskMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TagTaskMaxAggregateInputType
}

export type GetTagTaskAggregateType<T extends TagTaskAggregateArgs> = {
      [P in keyof T & keyof AggregateTagTask]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTagTask[P]>
    : Prisma.GetScalarType<T[P], AggregateTagTask[P]>
}




export type TagTaskGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TagTaskWhereInput
  orderBy?: Prisma.TagTaskOrderByWithAggregationInput | Prisma.TagTaskOrderByWithAggregationInput[]
  by: Prisma.TagTaskScalarFieldEnum[] | Prisma.TagTaskScalarFieldEnum
  having?: Prisma.TagTaskScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TagTaskCountAggregateInputType | true
  _min?: TagTaskMinAggregateInputType
  _max?: TagTaskMaxAggregateInputType
}

export type TagTaskGroupByOutputType = {
  tagId: string
  taskId: string
  _count: TagTaskCountAggregateOutputType | null
  _min: TagTaskMinAggregateOutputType | null
  _max: TagTaskMaxAggregateOutputType | null
}

export type GetTagTaskGroupByPayload<T extends TagTaskGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TagTaskGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TagTaskGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TagTaskGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TagTaskGroupByOutputType[P]>
      }
    >
  >



export type TagTaskWhereInput = {
  AND?: Prisma.TagTaskWhereInput | Prisma.TagTaskWhereInput[]
  OR?: Prisma.TagTaskWhereInput[]
  NOT?: Prisma.TagTaskWhereInput | Prisma.TagTaskWhereInput[]
  tagId?: Prisma.StringFilter<"TagTask"> | string
  taskId?: Prisma.StringFilter<"TagTask"> | string
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}

export type TagTaskOrderByWithRelationInput = {
  tagId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  tag?: Prisma.TagOrderByWithRelationInput
  task?: Prisma.TaskOrderByWithRelationInput
}

export type TagTaskWhereUniqueInput = Prisma.AtLeast<{
  tagId_taskId?: Prisma.TagTaskTagIdTaskIdCompoundUniqueInput
  AND?: Prisma.TagTaskWhereInput | Prisma.TagTaskWhereInput[]
  OR?: Prisma.TagTaskWhereInput[]
  NOT?: Prisma.TagTaskWhereInput | Prisma.TagTaskWhereInput[]
  tagId?: Prisma.StringFilter<"TagTask"> | string
  taskId?: Prisma.StringFilter<"TagTask"> | string
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
  task?: Prisma.XOR<Prisma.TaskScalarRelationFilter, Prisma.TaskWhereInput>
}, "tagId_taskId">

export type TagTaskOrderByWithAggregationInput = {
  tagId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  _count?: Prisma.TagTaskCountOrderByAggregateInput
  _max?: Prisma.TagTaskMaxOrderByAggregateInput
  _min?: Prisma.TagTaskMinOrderByAggregateInput
}

export type TagTaskScalarWhereWithAggregatesInput = {
  AND?: Prisma.TagTaskScalarWhereWithAggregatesInput | Prisma.TagTaskScalarWhereWithAggregatesInput[]
  OR?: Prisma.TagTaskScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TagTaskScalarWhereWithAggregatesInput | Prisma.TagTaskScalarWhereWithAggregatesInput[]
  tagId?: Prisma.StringWithAggregatesFilter<"TagTask"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"TagTask"> | string
}

export type TagTaskCreateInput = {
  tag: Prisma.TagCreateNestedOneWithoutTasksInput
  task: Prisma.TaskCreateNestedOneWithoutTagsInput
}

export type TagTaskUncheckedCreateInput = {
  tagId: string
  taskId: string
}

export type TagTaskUpdateInput = {
  tag?: Prisma.TagUpdateOneRequiredWithoutTasksNestedInput
  task?: Prisma.TaskUpdateOneRequiredWithoutTagsNestedInput
}

export type TagTaskUncheckedUpdateInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagTaskCreateManyInput = {
  tagId: string
  taskId: string
}

export type TagTaskUpdateManyMutationInput = {

}

export type TagTaskUncheckedUpdateManyInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagTaskListRelationFilter = {
  every?: Prisma.TagTaskWhereInput
  some?: Prisma.TagTaskWhereInput
  none?: Prisma.TagTaskWhereInput
}

export type TagTaskOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TagTaskTagIdTaskIdCompoundUniqueInput = {
  tagId: string
  taskId: string
}

export type TagTaskCountOrderByAggregateInput = {
  tagId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
}

export type TagTaskMaxOrderByAggregateInput = {
  tagId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
}

export type TagTaskMinOrderByAggregateInput = {
  tagId?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
}

export type TagTaskCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTaskInput, Prisma.TagTaskUncheckedCreateWithoutTaskInput> | Prisma.TagTaskCreateWithoutTaskInput[] | Prisma.TagTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTaskInput | Prisma.TagTaskCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TagTaskCreateManyTaskInputEnvelope
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
}

export type TagTaskUncheckedCreateNestedManyWithoutTaskInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTaskInput, Prisma.TagTaskUncheckedCreateWithoutTaskInput> | Prisma.TagTaskCreateWithoutTaskInput[] | Prisma.TagTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTaskInput | Prisma.TagTaskCreateOrConnectWithoutTaskInput[]
  createMany?: Prisma.TagTaskCreateManyTaskInputEnvelope
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
}

export type TagTaskUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTaskInput, Prisma.TagTaskUncheckedCreateWithoutTaskInput> | Prisma.TagTaskCreateWithoutTaskInput[] | Prisma.TagTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTaskInput | Prisma.TagTaskCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TagTaskUpsertWithWhereUniqueWithoutTaskInput | Prisma.TagTaskUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TagTaskCreateManyTaskInputEnvelope
  set?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  disconnect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  delete?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  update?: Prisma.TagTaskUpdateWithWhereUniqueWithoutTaskInput | Prisma.TagTaskUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TagTaskUpdateManyWithWhereWithoutTaskInput | Prisma.TagTaskUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TagTaskScalarWhereInput | Prisma.TagTaskScalarWhereInput[]
}

export type TagTaskUncheckedUpdateManyWithoutTaskNestedInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTaskInput, Prisma.TagTaskUncheckedCreateWithoutTaskInput> | Prisma.TagTaskCreateWithoutTaskInput[] | Prisma.TagTaskUncheckedCreateWithoutTaskInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTaskInput | Prisma.TagTaskCreateOrConnectWithoutTaskInput[]
  upsert?: Prisma.TagTaskUpsertWithWhereUniqueWithoutTaskInput | Prisma.TagTaskUpsertWithWhereUniqueWithoutTaskInput[]
  createMany?: Prisma.TagTaskCreateManyTaskInputEnvelope
  set?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  disconnect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  delete?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  update?: Prisma.TagTaskUpdateWithWhereUniqueWithoutTaskInput | Prisma.TagTaskUpdateWithWhereUniqueWithoutTaskInput[]
  updateMany?: Prisma.TagTaskUpdateManyWithWhereWithoutTaskInput | Prisma.TagTaskUpdateManyWithWhereWithoutTaskInput[]
  deleteMany?: Prisma.TagTaskScalarWhereInput | Prisma.TagTaskScalarWhereInput[]
}

export type TagTaskCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTagInput, Prisma.TagTaskUncheckedCreateWithoutTagInput> | Prisma.TagTaskCreateWithoutTagInput[] | Prisma.TagTaskUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTagInput | Prisma.TagTaskCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagTaskCreateManyTagInputEnvelope
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
}

export type TagTaskUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTagInput, Prisma.TagTaskUncheckedCreateWithoutTagInput> | Prisma.TagTaskCreateWithoutTagInput[] | Prisma.TagTaskUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTagInput | Prisma.TagTaskCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagTaskCreateManyTagInputEnvelope
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
}

export type TagTaskUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTagInput, Prisma.TagTaskUncheckedCreateWithoutTagInput> | Prisma.TagTaskCreateWithoutTagInput[] | Prisma.TagTaskUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTagInput | Prisma.TagTaskCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagTaskUpsertWithWhereUniqueWithoutTagInput | Prisma.TagTaskUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagTaskCreateManyTagInputEnvelope
  set?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  disconnect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  delete?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  update?: Prisma.TagTaskUpdateWithWhereUniqueWithoutTagInput | Prisma.TagTaskUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagTaskUpdateManyWithWhereWithoutTagInput | Prisma.TagTaskUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagTaskScalarWhereInput | Prisma.TagTaskScalarWhereInput[]
}

export type TagTaskUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagTaskCreateWithoutTagInput, Prisma.TagTaskUncheckedCreateWithoutTagInput> | Prisma.TagTaskCreateWithoutTagInput[] | Prisma.TagTaskUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagTaskCreateOrConnectWithoutTagInput | Prisma.TagTaskCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagTaskUpsertWithWhereUniqueWithoutTagInput | Prisma.TagTaskUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagTaskCreateManyTagInputEnvelope
  set?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  disconnect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  delete?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  connect?: Prisma.TagTaskWhereUniqueInput | Prisma.TagTaskWhereUniqueInput[]
  update?: Prisma.TagTaskUpdateWithWhereUniqueWithoutTagInput | Prisma.TagTaskUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagTaskUpdateManyWithWhereWithoutTagInput | Prisma.TagTaskUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagTaskScalarWhereInput | Prisma.TagTaskScalarWhereInput[]
}

export type TagTaskCreateWithoutTaskInput = {
  tag: Prisma.TagCreateNestedOneWithoutTasksInput
}

export type TagTaskUncheckedCreateWithoutTaskInput = {
  tagId: string
}

export type TagTaskCreateOrConnectWithoutTaskInput = {
  where: Prisma.TagTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.TagTaskCreateWithoutTaskInput, Prisma.TagTaskUncheckedCreateWithoutTaskInput>
}

export type TagTaskCreateManyTaskInputEnvelope = {
  data: Prisma.TagTaskCreateManyTaskInput | Prisma.TagTaskCreateManyTaskInput[]
  skipDuplicates?: boolean
}

export type TagTaskUpsertWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TagTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.TagTaskUpdateWithoutTaskInput, Prisma.TagTaskUncheckedUpdateWithoutTaskInput>
  create: Prisma.XOR<Prisma.TagTaskCreateWithoutTaskInput, Prisma.TagTaskUncheckedCreateWithoutTaskInput>
}

export type TagTaskUpdateWithWhereUniqueWithoutTaskInput = {
  where: Prisma.TagTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.TagTaskUpdateWithoutTaskInput, Prisma.TagTaskUncheckedUpdateWithoutTaskInput>
}

export type TagTaskUpdateManyWithWhereWithoutTaskInput = {
  where: Prisma.TagTaskScalarWhereInput
  data: Prisma.XOR<Prisma.TagTaskUpdateManyMutationInput, Prisma.TagTaskUncheckedUpdateManyWithoutTaskInput>
}

export type TagTaskScalarWhereInput = {
  AND?: Prisma.TagTaskScalarWhereInput | Prisma.TagTaskScalarWhereInput[]
  OR?: Prisma.TagTaskScalarWhereInput[]
  NOT?: Prisma.TagTaskScalarWhereInput | Prisma.TagTaskScalarWhereInput[]
  tagId?: Prisma.StringFilter<"TagTask"> | string
  taskId?: Prisma.StringFilter<"TagTask"> | string
}

export type TagTaskCreateWithoutTagInput = {
  task: Prisma.TaskCreateNestedOneWithoutTagsInput
}

export type TagTaskUncheckedCreateWithoutTagInput = {
  taskId: string
}

export type TagTaskCreateOrConnectWithoutTagInput = {
  where: Prisma.TagTaskWhereUniqueInput
  create: Prisma.XOR<Prisma.TagTaskCreateWithoutTagInput, Prisma.TagTaskUncheckedCreateWithoutTagInput>
}

export type TagTaskCreateManyTagInputEnvelope = {
  data: Prisma.TagTaskCreateManyTagInput | Prisma.TagTaskCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type TagTaskUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagTaskWhereUniqueInput
  update: Prisma.XOR<Prisma.TagTaskUpdateWithoutTagInput, Prisma.TagTaskUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.TagTaskCreateWithoutTagInput, Prisma.TagTaskUncheckedCreateWithoutTagInput>
}

export type TagTaskUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagTaskWhereUniqueInput
  data: Prisma.XOR<Prisma.TagTaskUpdateWithoutTagInput, Prisma.TagTaskUncheckedUpdateWithoutTagInput>
}

export type TagTaskUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.TagTaskScalarWhereInput
  data: Prisma.XOR<Prisma.TagTaskUpdateManyMutationInput, Prisma.TagTaskUncheckedUpdateManyWithoutTagInput>
}

export type TagTaskCreateManyTaskInput = {
  tagId: string
}

export type TagTaskUpdateWithoutTaskInput = {
  tag?: Prisma.TagUpdateOneRequiredWithoutTasksNestedInput
}

export type TagTaskUncheckedUpdateWithoutTaskInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagTaskUncheckedUpdateManyWithoutTaskInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagTaskCreateManyTagInput = {
  taskId: string
}

export type TagTaskUpdateWithoutTagInput = {
  task?: Prisma.TaskUpdateOneRequiredWithoutTagsNestedInput
}

export type TagTaskUncheckedUpdateWithoutTagInput = {
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagTaskUncheckedUpdateManyWithoutTagInput = {
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TagTaskSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tagId?: boolean
  taskId?: boolean
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagTask"]>

export type TagTaskSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tagId?: boolean
  taskId?: boolean
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagTask"]>

export type TagTaskSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tagId?: boolean
  taskId?: boolean
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagTask"]>

export type TagTaskSelectScalar = {
  tagId?: boolean
  taskId?: boolean
}

export type TagTaskOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"tagId" | "taskId", ExtArgs["result"]["tagTask"]>
export type TagTaskInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type TagTaskIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}
export type TagTaskIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
  task?: boolean | Prisma.TaskDefaultArgs<ExtArgs>
}

export type $TagTaskPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TagTask"
  objects: {
    tag: Prisma.$TagPayload<ExtArgs>
    task: Prisma.$TaskPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    tagId: string
    taskId: string
  }, ExtArgs["result"]["tagTask"]>
  composites: {}
}

export type TagTaskGetPayload<S extends boolean | null | undefined | TagTaskDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TagTaskPayload, S>

export type TagTaskCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TagTaskFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TagTaskCountAggregateInputType | true
  }

export interface TagTaskDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TagTask'], meta: { name: 'TagTask' } }
  /**
   * Find zero or one TagTask that matches the filter.
   * @param {TagTaskFindUniqueArgs} args - Arguments to find a TagTask
   * @example
   * // Get one TagTask
   * const tagTask = await prisma.tagTask.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TagTaskFindUniqueArgs>(args: Prisma.SelectSubset<T, TagTaskFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TagTask that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TagTaskFindUniqueOrThrowArgs} args - Arguments to find a TagTask
   * @example
   * // Get one TagTask
   * const tagTask = await prisma.tagTask.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TagTaskFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TagTaskFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagTask that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagTaskFindFirstArgs} args - Arguments to find a TagTask
   * @example
   * // Get one TagTask
   * const tagTask = await prisma.tagTask.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TagTaskFindFirstArgs>(args?: Prisma.SelectSubset<T, TagTaskFindFirstArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagTask that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagTaskFindFirstOrThrowArgs} args - Arguments to find a TagTask
   * @example
   * // Get one TagTask
   * const tagTask = await prisma.tagTask.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TagTaskFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TagTaskFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TagTasks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagTaskFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TagTasks
   * const tagTasks = await prisma.tagTask.findMany()
   * 
   * // Get first 10 TagTasks
   * const tagTasks = await prisma.tagTask.findMany({ take: 10 })
   * 
   * // Only select the `tagId`
   * const tagTaskWithTagIdOnly = await prisma.tagTask.findMany({ select: { tagId: true } })
   * 
   */
  findMany<T extends TagTaskFindManyArgs>(args?: Prisma.SelectSubset<T, TagTaskFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TagTask.
   * @param {TagTaskCreateArgs} args - Arguments to create a TagTask.
   * @example
   * // Create one TagTask
   * const TagTask = await prisma.tagTask.create({
   *   data: {
   *     // ... data to create a TagTask
   *   }
   * })
   * 
   */
  create<T extends TagTaskCreateArgs>(args: Prisma.SelectSubset<T, TagTaskCreateArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TagTasks.
   * @param {TagTaskCreateManyArgs} args - Arguments to create many TagTasks.
   * @example
   * // Create many TagTasks
   * const tagTask = await prisma.tagTask.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TagTaskCreateManyArgs>(args?: Prisma.SelectSubset<T, TagTaskCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TagTasks and returns the data saved in the database.
   * @param {TagTaskCreateManyAndReturnArgs} args - Arguments to create many TagTasks.
   * @example
   * // Create many TagTasks
   * const tagTask = await prisma.tagTask.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TagTasks and only return the `tagId`
   * const tagTaskWithTagIdOnly = await prisma.tagTask.createManyAndReturn({
   *   select: { tagId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TagTaskCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TagTaskCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TagTask.
   * @param {TagTaskDeleteArgs} args - Arguments to delete one TagTask.
   * @example
   * // Delete one TagTask
   * const TagTask = await prisma.tagTask.delete({
   *   where: {
   *     // ... filter to delete one TagTask
   *   }
   * })
   * 
   */
  delete<T extends TagTaskDeleteArgs>(args: Prisma.SelectSubset<T, TagTaskDeleteArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TagTask.
   * @param {TagTaskUpdateArgs} args - Arguments to update one TagTask.
   * @example
   * // Update one TagTask
   * const tagTask = await prisma.tagTask.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TagTaskUpdateArgs>(args: Prisma.SelectSubset<T, TagTaskUpdateArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TagTasks.
   * @param {TagTaskDeleteManyArgs} args - Arguments to filter TagTasks to delete.
   * @example
   * // Delete a few TagTasks
   * const { count } = await prisma.tagTask.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TagTaskDeleteManyArgs>(args?: Prisma.SelectSubset<T, TagTaskDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagTaskUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TagTasks
   * const tagTask = await prisma.tagTask.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TagTaskUpdateManyArgs>(args: Prisma.SelectSubset<T, TagTaskUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagTasks and returns the data updated in the database.
   * @param {TagTaskUpdateManyAndReturnArgs} args - Arguments to update many TagTasks.
   * @example
   * // Update many TagTasks
   * const tagTask = await prisma.tagTask.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TagTasks and only return the `tagId`
   * const tagTaskWithTagIdOnly = await prisma.tagTask.updateManyAndReturn({
   *   select: { tagId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TagTaskUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TagTaskUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TagTask.
   * @param {TagTaskUpsertArgs} args - Arguments to update or create a TagTask.
   * @example
   * // Update or create a TagTask
   * const tagTask = await prisma.tagTask.upsert({
   *   create: {
   *     // ... data to create a TagTask
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TagTask we want to update
   *   }
   * })
   */
  upsert<T extends TagTaskUpsertArgs>(args: Prisma.SelectSubset<T, TagTaskUpsertArgs<ExtArgs>>): Prisma.Prisma__TagTaskClient<runtime.Types.Result.GetResult<Prisma.$TagTaskPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TagTasks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagTaskCountArgs} args - Arguments to filter TagTasks to count.
   * @example
   * // Count the number of TagTasks
   * const count = await prisma.tagTask.count({
   *   where: {
   *     // ... the filter for the TagTasks we want to count
   *   }
   * })
  **/
  count<T extends TagTaskCountArgs>(
    args?: Prisma.Subset<T, TagTaskCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TagTaskCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TagTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagTaskAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TagTaskAggregateArgs>(args: Prisma.Subset<T, TagTaskAggregateArgs>): Prisma.PrismaPromise<GetTagTaskAggregateType<T>>

  /**
   * Group by TagTask.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagTaskGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TagTaskGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TagTaskGroupByArgs['orderBy'] }
      : { orderBy?: TagTaskGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TagTaskGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTagTaskGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TagTask model
 */
readonly fields: TagTaskFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TagTask.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TagTaskClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  task<T extends Prisma.TaskDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TaskDefaultArgs<ExtArgs>>): Prisma.Prisma__TaskClient<runtime.Types.Result.GetResult<Prisma.$TaskPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TagTask model
 */
export interface TagTaskFieldRefs {
  readonly tagId: Prisma.FieldRef<"TagTask", 'String'>
  readonly taskId: Prisma.FieldRef<"TagTask", 'String'>
}
    

// Custom InputTypes
/**
 * TagTask findUnique
 */
export type TagTaskFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * Filter, which TagTask to fetch.
   */
  where: Prisma.TagTaskWhereUniqueInput
}

/**
 * TagTask findUniqueOrThrow
 */
export type TagTaskFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * Filter, which TagTask to fetch.
   */
  where: Prisma.TagTaskWhereUniqueInput
}

/**
 * TagTask findFirst
 */
export type TagTaskFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * Filter, which TagTask to fetch.
   */
  where?: Prisma.TagTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagTasks to fetch.
   */
  orderBy?: Prisma.TagTaskOrderByWithRelationInput | Prisma.TagTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagTasks.
   */
  cursor?: Prisma.TagTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagTasks.
   */
  distinct?: Prisma.TagTaskScalarFieldEnum | Prisma.TagTaskScalarFieldEnum[]
}

/**
 * TagTask findFirstOrThrow
 */
export type TagTaskFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * Filter, which TagTask to fetch.
   */
  where?: Prisma.TagTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagTasks to fetch.
   */
  orderBy?: Prisma.TagTaskOrderByWithRelationInput | Prisma.TagTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagTasks.
   */
  cursor?: Prisma.TagTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagTasks.
   */
  distinct?: Prisma.TagTaskScalarFieldEnum | Prisma.TagTaskScalarFieldEnum[]
}

/**
 * TagTask findMany
 */
export type TagTaskFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * Filter, which TagTasks to fetch.
   */
  where?: Prisma.TagTaskWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagTasks to fetch.
   */
  orderBy?: Prisma.TagTaskOrderByWithRelationInput | Prisma.TagTaskOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TagTasks.
   */
  cursor?: Prisma.TagTaskWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagTasks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagTasks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagTasks.
   */
  distinct?: Prisma.TagTaskScalarFieldEnum | Prisma.TagTaskScalarFieldEnum[]
}

/**
 * TagTask create
 */
export type TagTaskCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * The data needed to create a TagTask.
   */
  data: Prisma.XOR<Prisma.TagTaskCreateInput, Prisma.TagTaskUncheckedCreateInput>
}

/**
 * TagTask createMany
 */
export type TagTaskCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TagTasks.
   */
  data: Prisma.TagTaskCreateManyInput | Prisma.TagTaskCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TagTask createManyAndReturn
 */
export type TagTaskCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * The data used to create many TagTasks.
   */
  data: Prisma.TagTaskCreateManyInput | Prisma.TagTaskCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TagTask update
 */
export type TagTaskUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * The data needed to update a TagTask.
   */
  data: Prisma.XOR<Prisma.TagTaskUpdateInput, Prisma.TagTaskUncheckedUpdateInput>
  /**
   * Choose, which TagTask to update.
   */
  where: Prisma.TagTaskWhereUniqueInput
}

/**
 * TagTask updateMany
 */
export type TagTaskUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TagTasks.
   */
  data: Prisma.XOR<Prisma.TagTaskUpdateManyMutationInput, Prisma.TagTaskUncheckedUpdateManyInput>
  /**
   * Filter which TagTasks to update
   */
  where?: Prisma.TagTaskWhereInput
  /**
   * Limit how many TagTasks to update.
   */
  limit?: number
}

/**
 * TagTask updateManyAndReturn
 */
export type TagTaskUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * The data used to update TagTasks.
   */
  data: Prisma.XOR<Prisma.TagTaskUpdateManyMutationInput, Prisma.TagTaskUncheckedUpdateManyInput>
  /**
   * Filter which TagTasks to update
   */
  where?: Prisma.TagTaskWhereInput
  /**
   * Limit how many TagTasks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TagTask upsert
 */
export type TagTaskUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * The filter to search for the TagTask to update in case it exists.
   */
  where: Prisma.TagTaskWhereUniqueInput
  /**
   * In case the TagTask found by the `where` argument doesn't exist, create a new TagTask with this data.
   */
  create: Prisma.XOR<Prisma.TagTaskCreateInput, Prisma.TagTaskUncheckedCreateInput>
  /**
   * In case the TagTask was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TagTaskUpdateInput, Prisma.TagTaskUncheckedUpdateInput>
}

/**
 * TagTask delete
 */
export type TagTaskDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
  /**
   * Filter which TagTask to delete.
   */
  where: Prisma.TagTaskWhereUniqueInput
}

/**
 * TagTask deleteMany
 */
export type TagTaskDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagTasks to delete
   */
  where?: Prisma.TagTaskWhereInput
  /**
   * Limit how many TagTasks to delete.
   */
  limit?: number
}

/**
 * TagTask without action
 */
export type TagTaskDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagTask
   */
  select?: Prisma.TagTaskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagTask
   */
  omit?: Prisma.TagTaskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagTaskInclude<ExtArgs> | null
}
