
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const TaskStatus = {
  NORMAL: 'NORMAL',
  COMPLETED: 'COMPLETED',
  ABANDONED: 'ABANDONED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]


export const TaskPriority = {
  NONE: 'NONE',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
} as const

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority]


export const ProjectKind = {
  INBOX: 'INBOX',
  LIST: 'LIST',
  PROJECT: 'PROJECT'
} as const

export type ProjectKind = (typeof ProjectKind)[keyof typeof ProjectKind]


export const ProjectView = {
  LIST: 'LIST',
  KANBAN: 'KANBAN',
  TIMELINE: 'TIMELINE',
  CALENDAR: 'CALENDAR'
} as const

export type ProjectView = (typeof ProjectView)[keyof typeof ProjectView]


export const MemberRole = {
  OWNER: 'OWNER',
  EDITOR: 'EDITOR',
  VIEWER: 'VIEWER'
} as const

export type MemberRole = (typeof MemberRole)[keyof typeof MemberRole]


export const HabitFrequency = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY'
} as const

export type HabitFrequency = (typeof HabitFrequency)[keyof typeof HabitFrequency]


export const HabitStatus = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  ARCHIVED: 'ARCHIVED'
} as const

export type HabitStatus = (typeof HabitStatus)[keyof typeof HabitStatus]


export const FocusType = {
  POMODORO: 'POMODORO',
  STOPWATCH: 'STOPWATCH'
} as const

export type FocusType = (typeof FocusType)[keyof typeof FocusType]
